[package]
name = "keplr-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "keplr"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
keplr-core = { path = "../keplr-core" }
keplr-build = { path = "../keplr-build" }
keplr-lang = { path = "../keplr-lang" }
keplr-sync = { path = "../keplr-sync" }
keplr-serve = { path = "../keplr-serve" }
keplr-render = { path = "../keplr-render" }
keplr-ui = { path = "../keplr-ui" }
tokio.workspace = true
crossterm.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
http.workspace = true

[features]
desktop = ["keplr-render/gpu"]
