[package]
name = "keplr-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "keplr"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
keplr-core = { path = "../keplr-core" }
keplr-build = { path = "../keplr-build" }
keplr-lang = { path = "../keplr-lang" }
keplr-sync = { path = "../keplr-sync" }
keplr-serve = { path = "../keplr-serve" }
tokio.workspace = true
