[package]
name = "keplr-serve"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
keplr-core = { path = "../keplr-core" }
keplr-build = { path = "../keplr-build" }
keplr-render = { path = "../keplr-render" }
keplr-lang = { path = "../keplr-lang" }
keplr-sync = { path = "../keplr-sync" }
portable-pty.workspace = true
alacritty_terminal.workspace = true

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
