[package]
name = "keplr-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen.workspace = true
serde.workspace = true
serde_json.workspace = true
keplr-lang = { path = "../keplr-lang" }
keplr-render = { path = "../keplr-render" }

[dependencies.web-sys]
workspace = true
features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
]
